name: Main

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          mkdir release
          echo "New 1" > release/1.txt
          echo "New 3" > release/3.txt
      - name: Upload assets to release
        run: gh release upload nightly release/* --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
