name: Main

on:
  push:
    tags:        
      - '*' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          mkdir public && cd public
          echo "1" > 1.txt
          echo "2" > 2.txt
          echo "CREATED_FILES=public/$(ls .)" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${CREATED_FILES}
