name: Main

on:
  push:
    tags:        
      - '*' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          mkdir public
          echo "1" > public/1.txt
          echo "2" > public/2.txt
          DIR_LISTING=$(ls \
          -1)
          echo "CREATED_FILES=${DIR_LISTING}" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${CREATED_FILES}
